### ISSUE TITLE
To Compose or Not To Compose?

### ISSUE THREAD

**Issue by NogsMPLS** [DigitalRiver/react-atlas#22]
Right now in our CSS we are using CSS Modules `composes` functionality. This allows us to actually reuse classes throughout our library.
### Example:

``` css
/* colors.css */
.green {
    color: green;
}
```

``` css
/* layout.css */
.block {
    display: block;
}
```

``` css
/* someComponent.css */
.base {
    composes: block from '../layout.css';
    composes: green from '../colors.css';
    font-size: 14px;
}
```

``` html
<!--someComponent HTML output -->
<div classes="ra_someComponent_base ra_layout_block ra_colors_green">
```
### CSS or HTML?

When above technique is applied across the entire library, we get truly re-usable classes and a very minified and small CSS file for styling our app. There is also the possible benefit of being able to easily override certain things like `.ra_colors_green` to match any brand's particular green/success color. Though that will take a bit more investigating.

However, a possible downside to this technique, is that it makes the HTML quite a bit longer. It's not hard to envision a component with 10+ classes attached to it. In fact, our Outline Button component currently has 13 classes attached to it. Most of those are atomic single purpose classes.

So the question here is:
Do we bloat our CSS filesize or do we bloat our HTML filesize?
Are there any good perf metrics out there moving one toward the other?
Where is the tipping point for either direction?
